version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: setup docker-compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: build
          command: |
            make build-all
      - run:
          name: running test 
          command: |
            make test-all
