version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            make build-all
          name: running test 
          command: |
            make test-all
